module.exports.descriptors = [
    'Florestal',
    'Velhote',
    'Petrificado',
    'Rompante',
    'Cascato',
    'Trapalhão',
    'Silente',
    'Pedroso',
    'Abandonado',
    'Neboloso',
    'Enraizado',
    'Ermo',
    'Destemperado',
    'Oceânico',
    'Marado',
    'Alado',
    'Selvagem',
    'Diabólico'
]

module.exports.places = [
    'Parque',
    'Monte',
    'Palito',
    'Poço',
    'Campo',
    'Campino',
    'Urbano',
    'Local',
    'Campo Disperso',
    'Riacho',
    'Rio',
    'Beco',
    'Canto',
    'Baldío',
    'Primaveril',
    'Costa',
    'Paço',
    'Passadiço',
    'Sítio',
    'Penhasco',
    'Vazio'
]

